export interface BuyerDetails{
    serialNumber: number,
    buyerId: any, 
    auditInsertTimestamp: any, 
    buyerUserName: string,
    operationType: any, 
    mainCartItemCount: any, 
    errorNames: any, 
    calLink: any, 
    cartItems: any, 
    downstreamUnknownErrors: any, 
    eventType: any, 
    externalErrornames: any, 
    guestUser: any, 
    buyerGuid: any, 
    notificationNames: any, 
    responseType: any, 
    sflItemCOunt: any, 
    clientAppName: any, 
    siteId: any, 
    countOfitemsToCheckout: any, 
    checkoutType: any, 
    itemsToCheckout: any, 
    checkoutCartFilterReason: any, 
    checkoutSessionTocken: any
}